site_name: Maxar Portal Services


nav:
    - Home: 'index.md'
    - OGC:
        - Quickstart: 'ogc/quickstart.md'
        - Search: 'ogc/image_search.md'
        - Download:
            - 'ogc/download_image.md'
            - 'ogc/download_browse_image.md'
            - 'ogc/download_image_featureid.md'
            - 'ogc/download_image_pixel_count.md'
            - 'ogc/download_tiles.md'
            - 'ogc/get_full_res_image.md'
        - 'Other':
            - 'ogc/band_manipulation.md'
            - 'ogc/create_mosaic.md'
            - 'ogc/get_filter_parameters.md'
    - Admin:
        - Quickstart: 'account-service/quickstart.md'
        - Search: 'account-service/accounts/Search.md'
        - Accounts:
            - 'account-service/accounts/Accounts.md'
            - 'account-service/accounts/Comments.md'
            - 'account-service/accounts/Roles.md'
            - 'account-service/activations/Activations.md'
            - 'account-service/usage/Usage.md'
        - Products:
            - 'account-service/products/Products.md'
            - Rate Tables: 'account-service/rate_tables/Rate_Tables.md'
        - Users:
            - 'account-service/users/Roles.md'
            - 'account-service/users/Users.md'
        - Tokens:
              - 'token-service/tokens.md'
        - Roles:
            - 'account-service/roles/Roles.md'
#    - Ordering:
#        - 'ordering.md'
    - Misc:
        - 'cli_commands.md'
    - 'Release Notes':
        - 'release_notes.md'

docs_dir: 'docs'
site_dir: 'site'
theme:
  name: material
  logo: maxar_gold_logo_rgb_250.png
  favicon: favicon.ico
  custom_dir: 'docs/stylesheets'
extra_css: 
    - stylesheets/extra.css

